// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxMUDZ5A4qfr04SE_tv1DS5Dpp8VvNvM',
    appId: '1:979385549611:web:e92194214b650b1b353b6e',
    messagingSenderId: '979385549611',
    projectId: 'rixa-b52b5',
    authDomain: 'rixa-b52b5.firebaseapp.com',
    storageBucket: 'rixa-b52b5.appspot.com',
    measurementId: 'G-HM75NZ867W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIEBxJWmUICbGaLeYsPCC5-V7d4PLr_Q',
    appId: '1:979385549611:android:c8edbbb760b645d0353b6e',
    messagingSenderId: '979385549611',
    projectId: 'rixa-b52b5',
    storageBucket: 'rixa-b52b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7dHaDAQquyQQgTg1QISgikUQ0E06pAs',
    appId: '1:979385549611:ios:13054bda7eac3252353b6e',
    messagingSenderId: '979385549611',
    projectId: 'rixa-b52b5',
    storageBucket: 'rixa-b52b5.appspot.com',
    iosClientId: '979385549611-0v76kcva5ud0n3r2a28i23d65krq87fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.rixa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7dHaDAQquyQQgTg1QISgikUQ0E06pAs',
    appId: '1:979385549611:ios:13054bda7eac3252353b6e',
    messagingSenderId: '979385549611',
    projectId: 'rixa-b52b5',
    storageBucket: 'rixa-b52b5.appspot.com',
    iosClientId: '979385549611-0v76kcva5ud0n3r2a28i23d65krq87fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.rixa',
  );
}
